### ISSUE TITLE
Clarification on breaking change with list card?

### ISSUE THREAD

**Issue by rpitera** [custom-components/feedparser#21]
> Note: This is a breaking change for the https://github.com/custom-cards/list-card
> I don't have an expected date on when I'll get around to fixing it. If you're using the list-card, do not upgrade to 0.0.8 for now.

Could you clarify what the breaking change is?  If you weren't to use list-card, what would be the alternative to showing the sensor's output?

Thanks!

**Comment by iantrich** [comment]
The change was how the feed is represented in the sensor, so how the list-card iterates through is not the same.

**Comment by iantrich** [comment]
Here's what a feed looks like right now
![image](https://user-images.githubusercontent.com/1287159/62296429-a8837f80-b434-11e9-8de7-81776298131e.png)

**Comment by iantrich** [comment]
As for what you would use, people wanted this change to more easily use it with template sensors

**Comment by rpitera** [comment]
Thanks, that was a big help in understanding things.  Given my primary use case, the list card still seems to be the way to go for me but I will keep following this to see how things progress.  I'm interested how people use this with a template sensor; hopefully someone will post an example or two.  In the meantime you can close this and thanks for the explanation.

**Comment by Spankythemusical** [comment]
How can we revert back to the earlier version?

**Comment by roblandry** [comment]
Is this still an issue?
