### ISSUE TITLE
Component doesn't comply with manifest content requirement

### ISSUE THREAD

**Issue by Sudo-Rob** [custom-components/feedparser#33]
This message appears in home-assistant.log:

`(MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'feedparser'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'feedparser'`

**Comment by raw99** [comment]
#34

**Comment by Sudo-Rob** [comment]
It works.  Will you merge it into a HACS release?
