### ISSUE TITLE
stopped working with latest update

### ISSUE THREAD

**Issue by ghvader** [custom-components/feedparser#37]
You are running Home Assistant version '2021.3.4', but this repository requires minimum version '2021.4' to be installed

21.4 isn't out for several more days. after i updated today, it no longer works

the code change yesterday broke it
ImportError: cannot import name 'SensorEntity' from 'homeassistant.helpers.entity'

**Comment by jazzyisj** [comment]
You have 3 options.

- Reinstall the previous version of feed parser until 2021.4 is available 
- Install the beta version of 2021.4 
- Live with the warning in your log for a few days.

**Comment by ghvader** [comment]
> You have 3 options.
> 
> * Reinstall the previous version of feed parser until 2021.4 is available
> * Install the beta version of 2021.4
> * Live with the warning in your log for a few days.

it's not a warning, it's an error and it doesn't work at all. hacs prevents me from installing anything due to the minimum version requirements. I can manually re-install via cli, but just wanted to give a heads up to anyone else who has this problem (i would suspect everyone no?) ImportError: cannot import name 'SensorEntity' from 'homeassistant.helpers.entity' is what i see in my logs

**Comment by jazzyisj** [comment]
I imagine everyone would have this issue.  I ended up on the git to manually downgrade myself.  

I think the inability to downgrade is a "bug" with HACS though - it should only stop you from installing the latest version, not downgrading to a working version (and it really should have stopped us from upgrading it in the first place).  

Not much iantrich can do about that.

**Comment by alundstroem** [comment]
I just used the hassio addon "File editor" and replaced two occurencies of "SensorEntity" with "Entity" in feedparser/sensor.py and its back up again

**Comment by ghvader** [comment]
> I just used the hassio addon "File editor" and replaced two occurencies of "SensorEntity" with "Entity" in feedparser/sensor.py and its back up again

I can confirm this worked for me as well.

**Comment by groenmarsmannetje** [comment]
The release should be rolled back asap as it was released too soon. I cannot even restart HA anymore in UI because of this issue. Very annoying. A manual code change by users is not a solution at all.

**Comment by iantrich** [comment]
The recommended solution is to downgrade, not edit the code

**Comment by iantrich** [comment]
Try 0.1.5

**Comment by alundstroem** [comment]
Thanks, that seems to work just fine
