### ISSUE TITLE
cannot install, version mismatch

### ISSUE THREAD

**Issue by thewan056** [custom-components/feedparser#38]
![Screenshot 2021-04-08 160115](https://user-images.githubusercontent.com/24851051/113990101-b503e080-9883-11eb-8a8d-408398fa4779.jpg)

As per screenshot. I just found this integration after updating my HA. Did I update it wrong?

**Comment by damanti-me** [comment]
had the same issue. 
Solution for me: copy the github folder regarding the instruction (To get started put /custom_components/feedparser/ here: <config directory>/custom_components/feedparser/). Then change some text (https://github.com/custom-components/feedparser/issues/37#issuecomment-813886604) 
a lot workaround but it works for me now

**Comment by iantrich** [comment]
I'll get it fixed later today hopefully

**Comment by iantrich** [comment]
I think it should be fixed now. Had to change the minimum version to `2021.4.0` instead of `2021.4`. Able to install on my production machine running 2021.4.0 now

**Comment by damanti-me** [comment]
thanks for your work!
