### ISSUE TITLE
Add Version key in manifest file

### ISSUE THREAD

**Issue by jokerigno** [custom-components/feedparser#43]
Hi,

I found a warning message in logs. I'm quite sure that you already know it but if don't please have a look at it:

No 'version' key in the manifest file for custom integration 'feedparser'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'feedparser.

**Comment by jokerigno** [comment]
Hi, component now is not loading without version key in manifest file.

**Comment by iantrich** [comment]
It's there?
https://github.com/custom-components/feedparser/blob/master/custom_components/feedparser/manifest.json#L4

**Comment by wuschel1337** [comment]
What is mean witch version key? My manifest looks the same like ianreich. 
My parser is working under 2021.6.2, but only for 1 site (the first in configuration.yaml), 2 other sites will not shown. 
Have u a solution or idea?!
