### ISSUE TITLE
Feature request: Make scan interval configurable

### ISSUE THREAD

**Issue by sgofferj** [custom-components/feedparser#46]
For high activity or high importance feeds, it would be very useful to be able to configure the scan interval. Examples include information and warning feeds of emergency services and public safety authorities. One hour is too long to use those feeds effectively.

**Comment by slankes** [comment]
I second this but from the other direction - if I just want the latest podcast episode, then once or twice a day is plenty.

**Comment by iantrich** [comment]
I'm not really able to spend any time on this currently. PRs welcome.

**Comment by iantrich** [comment]
should be fixed in 0.1.8

**Comment by sgofferj** [comment]
Is the scan_interval really in hours or is that a typo in the docs?

**Comment by Paktas** [comment]
> Is the scan_interval really in hours or is that a typo in the docs?

For refreshing the news pieces - we need **more frequent** updates than just once per hour. We are looking into refreshed every 30 minutes. Hope this can be updated.
